import json
import os
import argparse
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE

def create_slideshow(json_file, project_path, output_pptx):
    # Read JSON data
    scenes = []
    with open(json_file, 'r', encoding='utf-8') as f:
        for line in f:
            try:
                data = json.loads(line)
                # Only include scene data (exclude metadata)
                if 'dialogue' in data or 'background' in data or 'sprites' in data:
                    scenes.append(data)
            except json.JSONDecodeError:
                continue
    
    # Create presentation
    prs = Presentation()
    
    # Slide dimensions
    slide_width = prs.slide_width
    slide_height = prs.slide_height
    
    # Add title slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = title_slide.shapes.title
    subtitle = title_slide.placeholders[1]
    
    title.text = "Ren'Py Visual Novel"
    subtitle.text = f"Generated from {os.path.basename(project_path)}"
    
    # Process each scene
    for i, scene in enumerate(scenes):
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
        
        # Add background image if available
        bg = scene.get('background')
        if bg:
            bg_path = os.path.join(project_path, bg)
            if os.path.exists(bg_path):
                slide.shapes.add_picture(
                    bg_path, 0, 0, width=slide_width, height=slide_height
                )
        
        # Add sprites (handling both string and dictionary formats)
        sprites = scene.get('sprites', {})
        for pos, sprite in sprites.items():
            # Handle both string sprite paths and dictionary sprite definitions
            sprite_image = sprite['image'] if isinstance(sprite, dict) else sprite
            sprite_path = os.path.join(project_path, sprite_image)
            
            if os.path.exists(sprite_path):
                width = Inches(4)
                y_pos = slide_height - Inches(5)  # Fixed Y position
                
                # Calculate X position based on keyword
                if 'left' in pos:
                    x_pos = Inches(0.5)
                elif 'right' in pos:
                    x_pos = slide_width - width - Inches(0.5)
                else:  # center/default
                    x_pos = (slide_width - width) / 2
                
                slide.shapes.add_picture(
                    sprite_path, 
                    x_pos, 
                    y_pos, 
                    width=width
                )
        
        # Add dialogue box
        dialogue = scene.get('dialogue', [])
        if dialogue:
            # Create rounded rectangle for dialogue box
            dialogue_box = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE, 
                Inches(0.5), 
                slide_height - Inches(2.5), 
                slide_width - Inches(1), 
                Inches(2)
            )
            # Set background color (semi-transparent black)
            fill = dialogue_box.fill
            fill.solid()
            fill.fore_color.rgb = RGBColor(0, 0, 0)
            fill.transparency = 0.25
            
            # Set border
            line = dialogue_box.line
            line.color.rgb = RGBColor(0, 0, 0)
            line.width = Pt(1.5)
            
            # Configure text frame
            text_frame = dialogue_box.text_frame
            text_frame.word_wrap = True
            text_frame.vertical_anchor = 1  # Middle
            
            for entry in dialogue:
                p = text_frame.add_paragraph()
                if entry.get('speaker'):
                    p.text = f"{entry['speaker']}: {entry['text']}"
                else:
                    p.text = entry['text']
                p.font.size = Pt(14)
                p.font.color.rgb = RGBColor(255, 255, 255)  # White text
                p.alignment = PP_ALIGN.LEFT
    
    # Save presentation
    prs.save(output_pptx)
    print(f"Created PowerPoint with {len(scenes)} slides at {output_pptx}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert Ren'Py JSON output to PowerPoint")
    parser.add_argument("json_file", help="JSON file generated by the parser")
    parser.add_argument("project_path", help="Path to Ren'Py project directory")
    parser.add_argument("output_pptx", help="Output PowerPoint file path")
    args = parser.parse_args()
    
    if not os.path.exists(args.json_file):
        print(f"Error: JSON file not found at {args.json_file}")
        exit(1)
    
    if not os.path.exists(args.project_path):
        print(f"Error: Project directory not found at {args.project_path}")
        exit(1)
    
    create_slideshow(args.json_file, args.project_path, args.output_pptx)
